# image will be published to ghcr.io/<user>/<name>
name: bluerulent-lp
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common.yml
  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/dsommers/openvpn3/repo/fedora-%OS_VERSION%/dsommers-openvpn3-fedora-%OS_VERSION%.repo
    install: 
      - openvpn3
#  - type: containerfile
#    snippets: 
#      - COPY --from=ghcr.io/ublue-os/akmods:main-39 /rpms/ /tmp/rpms
#  - type: akmods
#    install:
#      - evdi
